/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import practicaB.*;

/**
 *
 * @author USER
 */
public class AlgortimosDireccionales extends javax.swing.JPanel {

    private MainVisual mainV;
    private PracticaBMenu pB;

    private SolucionB sol = null;

    /**
     * Creates new form AlgortimosDireccionalesPanel
     */
    public AlgortimosDireccionales(MainVisual mainV, PracticaBMenu pB) {
        initComponents();

        this.mainV = mainV;
        this.pB = pB;
    }

    public void setLabelTitulo(String s) {
        lbtitulo.setText(s);
    }

    public String getLabelTitulo() {
        return lbtitulo.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtitulo = new javax.swing.JLabel();
        btvolvermenu = new javax.swing.JButton();
        btejecutar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        btgraficar = new javax.swing.JButton();

        lbtitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbtitulo.setText("Unidireccional");

        btvolvermenu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btvolvermenu.setText("Volver al Menu");
        btvolvermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvolvermenubtVolverMenu(evt);
            }
        });

        btejecutar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btejecutar.setText("Ejecutar");
        btejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEjecutar(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Distancia", "Punto Origen", "Punto Destino"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        texto.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jScrollPane1.setViewportView(texto);

        btgraficar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btgraficar.setText("Graficar Solucion");
        btgraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGraficar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btvolvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btgraficar, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btgraficar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btvolvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btvolvermenubtVolverMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvolvermenubtVolverMenu
        mainV.btCambiarPracticaToF(true);
        mainV.cambiarPanel(pB);
        this.setVisible(false);
    }//GEN-LAST:event_btvolvermenubtVolverMenu

    private void btEjecutar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEjecutar
        if (getLabelTitulo().equals("Unidireccional")) {
            sol = AlgoritmosVoraces.unidireccional(PracticaBMenu.dataSetB);
            int opc = JOptionPane.showConfirmDialog(this,
                    "¿Quieres generar el fichero con la solucion?", "", JOptionPane.YES_NO_OPTION);
            
            if(opc == 0)
                AlgoritmosVoraces.generarFichero(sol, "UNIDIRECCIONAL");
            
        } else {
            sol = AlgoritmosVoraces.bidireccional(PracticaBMenu.dataSetB);
            int opc = JOptionPane.showConfirmDialog(this,
                    "¿Quieres generar el fichero con la solucion?", "", JOptionPane.YES_NO_OPTION);
            
            if(opc == 0)
                AlgoritmosVoraces.generarFichero(sol, "UNIDIRECCIONAL");
            
        }

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Distancia", "Punto Origen", "Punto Destino"});

        int[] ruta = sol.getRuta();
        ArrayList<Double> distancias = sol.getDistancias();

        for (int i = 0; i < ruta.length - 1; i++) {
            dtm.addRow(new Object[]{distancias.get(i), ruta[i], ruta[i + 1]});
        }

        dtm.addRow(new Object[]{null, ruta[ruta.length - 1], null});
        texto.setText("Distancia total: " + sol.getDistanciatotal());
        tabla.setModel(dtm);
    }//GEN-LAST:event_btEjecutar

    private void btGraficar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGraficar
        if (sol != null) {
            new Graficar(PracticaBMenu.dataSetB, null, sol);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Antes debes darle al boton de ejecutar",
                    "INFO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btGraficar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btejecutar;
    private javax.swing.JButton btgraficar;
    private javax.swing.JButton btvolvermenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JTable tabla;
    private javax.swing.JTextPane texto;
    // End of variables declaration//GEN-END:variables
}
