/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual;

import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import practica1.Algoritmos;
import Comun.Lectura;
import Comun.Punto;
import javax.swing.JOptionPane;
import practica1.Solucion;

/**
 *
 * @author USER
 */
public class ComprobarEstrategia extends javax.swing.JPanel {

    private MainVisual mainV;
    private PracticaMenu p1;

    private Solucion sol = null;

    /**
     * Creates new form ComprobarEstrategiaPane
     */
    public ComprobarEstrategia(MainVisual m, PracticaMenu p) {
        initComponents();

        mainV = m;
        p1 = p;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btvolvermenu = new javax.swing.JButton();
        lbtitulo = new javax.swing.JLabel();
        btejecutar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbtabla = new javax.swing.JTable();
        btgraficar = new javax.swing.JButton();

        btvolvermenu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btvolvermenu.setText("Volver al Menu");
        btvolvermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverMenu(evt);
            }
        });

        lbtitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbtitulo.setText("Comprobar Estrategia");

        btejecutar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btejecutar.setText("Ejecutar");
        btejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEjecutar(evt);
            }
        });

        tbtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Estrategia", "Punto 1", "Punto 2", "Distancia", "Calculadas", "Tiempo (mseg)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbtabla);

        btgraficar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btgraficar.setText("Graficar Solución");
        btgraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGraficarSolucion(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(lbtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btgraficar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btvolvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbtitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btgraficar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btvolvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btVolverMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverMenu
        mainV.cambiarPanel(p1);
        this.setVisible(false);
    }//GEN-LAST:event_btVolverMenu

    private void btEjecutar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEjecutar

        DefaultTableModel dtm = new DefaultTableModel();
        String s[] = {"Estrategia", "Punto 1", "Punto 2", "Distancia", "Calculadas", "Tiempo(mseg)"};
        dtm.setColumnIdentifiers(s);

        String cadena = p1.getLbDataSet() + ".tsp\nEstrategia\t    Punto 1\t\tPunto 2\t\tDistancia\tTiempo\tCalculadas";
        DecimalFormat df = new DecimalFormat("#0.00000000");

        long t1 = System.nanoTime();
        sol = Algoritmos.exhaustivoRecursivo((ArrayList<Punto>) PracticaMenu.dataSet.clone());
        long t2 = System.nanoTime();
        double aux = (double) (t2 - t1) / 1000000;
        dtm.addRow(new Object[]{"Exhaustivo", sol.getP1(), sol.getP2(), df.format(sol.getDist()), sol.getCalculadas(), aux});
        Lectura.generarSolucionCE("Exhaustivo", sol.getP1().toString(), sol.getP1().toString(), sol.getDist(), aux);

        t1 = System.nanoTime();
        sol = Algoritmos.exhaustivoPodaRecursivo((ArrayList<Punto>) PracticaMenu.dataSet.clone());
        t2 = System.nanoTime();
        aux = (double) (t2 - t1) / 1000000;
        dtm.addRow(new Object[]{"Exhaustivo P", sol.getP1(), sol.getP2(), df.format(sol.getDist()), sol.getCalculadas(), aux});
        Lectura.generarSolucionCE("Exhaustivo Poda", sol.getP1().toString(), sol.getP1().toString(), sol.getDist(), aux);

        t1 = System.nanoTime();
        sol = Algoritmos.DyVRecursivo((ArrayList<Punto>) PracticaMenu.dataSet.clone());
        t2 = System.nanoTime();
        aux = (double) (t2 - t1) / 1000000;
        dtm.addRow(new Object[]{"Divide y Venceras", sol.getP1(), sol.getP2(), df.format(sol.getDist()), sol.getCalculadas(), aux});

        Lectura.generarSolucionCE("Divide y Venceras", sol.getP1().toString(), sol.getP1().toString(), sol.getDist(), aux);

        t1 = System.nanoTime();
        sol = Algoritmos.DyVconPodaRecursivo((ArrayList<Punto>) PracticaMenu.dataSet.clone());
        t2 = System.nanoTime();
        aux = (double) (t2 - t1) / 1000000;
        dtm.addRow(new Object[]{"Divide y Venceras M", sol.getP1(), sol.getP2(), df.format(sol.getDist()), sol.getCalculadas(), aux});
        Lectura.generarSolucionCE("Divide y Venceras Mejorado", sol.getP1().toString(), sol.getP1().toString(), sol.getDist(), aux);

        tbtabla.setModel(dtm);
    }//GEN-LAST:event_btEjecutar

    private void btGraficarSolucion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGraficarSolucion
        if (sol != null) {
            new Graficar(PracticaMenu.dataSet, sol);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Debes ejecutar primero para poder mostrar la grafica",
                    "INFO", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btGraficarSolucion


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btejecutar;
    private javax.swing.JButton btgraficar;
    private javax.swing.JButton btvolvermenu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JTable tbtabla;
    // End of variables declaration//GEN-END:variables
}
