/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Comun.Lectura;
import Comun.Punto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import practicaB.AlgoritmosVoraces;
import practicaB.SolucionB;

/**
 *
 * @author USER
 */
public class CompararAlgoritmosVoraces extends javax.swing.JFrame {

    /**
     * Creates new form CompararAalgoritmosVoraces
     */
    public CompararAlgoritmosVoraces() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbtitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btejecutar = new javax.swing.JButton();
        btvolvermenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbtitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbtitulo.setText("Comparación de Algoritmos");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Talla", "Unidireccional (Tm)", "Bidireccional (Tm)", "Unidireccional (MR)", "Bidireccional (MR)"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btejecutar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btejecutar.setText("Ejecutar");
        btejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEjecutar(evt);
            }
        });

        btvolvermenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btvolvermenu.setText("Volver al Menu");
        btvolvermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverMenu(evt);
            }
        });

        jLabel2.setText("(Tm) = Tiempo medio en mseg");

        jLabel3.setText("(MR) = mejor resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btvolvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(lbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(162, 162, 162)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btvolvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVolverMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverMenu
        this.setVisible(false);
    }//GEN-LAST:event_btVolverMenu

    private void btEjecutar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEjecutar
        int opc = JOptionPane.showConfirmDialog(this,
                "El proceso llevará unos minutos\n¿Quieres ejecutarlo?", "", JOptionPane.YES_NO_OPTION);

        if (opc == 0) {
            SolucionB solUni = new SolucionB();
            SolucionB solBi = new SolucionB();
            DefaultTableModel dtm = new DefaultTableModel();
            ArrayList<Punto> puntos;

            String[] s = {"Talla", "Unidireccional (Tm)", "Bidireccional (Tm)", "Unidireccional (MR)", "Bidireccional (MR)"};
            dtm.setColumnIdentifiers(s);

            for (int i = 500; i <= 5000; i += 500) {
                int mejorresultuni = 0, mejorresultbi = 0;
                double tmediouni = 0, tmediobi = 0;

                Lectura.generarDataSet(i, false);
                puntos = Lectura.leerFichero("DataSet" + i + ".tsp");

                for (int j = 0; j < 100; j++) {
                    long tiuni = System.nanoTime();
                    solUni = AlgoritmosVoraces.unidireccional(puntos);
                    long tfuni = System.nanoTime();
                    tmediouni += (double) (tfuni - tiuni) / 1000000;
                    
                    long tibi = System.nanoTime();
                    solBi = AlgoritmosVoraces.bidireccional(puntos);
                    long tfbi = System.nanoTime();
                    tmediobi += (double) (tfbi - tibi) / 1000000;
                    
                    if(solBi.getDistanciatotal() < solUni.getDistanciatotal()){
                        mejorresultbi++;
                    }else{
                        mejorresultuni++;
                    }
                }
                tmediouni = tmediouni/100;
                tmediobi = tmediobi/100;
                
                dtm.addRow(new Object[]{i, tmediouni, tmediobi, mejorresultuni, mejorresultbi});
            }
            
            System.out.println("FIN COMPARACIÓN");
            tabla.setModel(dtm);
        }

    }//GEN-LAST:event_btEjecutar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btejecutar;
    private javax.swing.JButton btvolvermenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
