/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import practica1.Algoritmos;
import Comun.Lectura;
import Comun.Punto;
import practica1.Solucion;

/**
 *
 * @author USER
 */
public class CompararTodasEstrategias extends javax.swing.JPanel {

    private MainVisual mainV;
    private PracticaMenu p1;

    /**
     * Creates new form ComprobarTodosAlgortimosPanel
     */
    public CompararTodasEstrategias(MainVisual m, PracticaMenu p) {
        initComponents();

        mainV = m;
        p1 = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btvolvermenu = new javax.swing.JButton();
        lbtitulo = new javax.swing.JLabel();
        btejecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpane = new javax.swing.JTextArea();

        btvolvermenu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btvolvermenu.setText("Volver al Menu");
        btvolvermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverMenu(evt);
            }
        });

        lbtitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbtitulo.setText("Comparar todas las estrategias");

        btejecutar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btejecutar.setText("Ejecutar");
        btejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEjecutar(evt);
            }
        });

        txtpane.setColumns(20);
        txtpane.setRows(5);
        jScrollPane1.setViewportView(txtpane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(btvolvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbtitulo)
                        .addGap(212, 212, 212))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbtitulo)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btvolvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btVolverMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverMenu
        mainV.cambiarPanel(p1);
        this.setVisible(false);
    }//GEN-LAST:event_btVolverMenu

    private void btEjecutar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEjecutar
        String cadena = "\tExhaustivo\tExhaustivoP\tDyV\tDyV Mejorado\nTalla\tTiempo(mseg)\tTiempo(mseg)\tTiempo(mseg)\tTiempo(mseg)";
        long t1, t2;
        double aux;
        Solucion sol = new Solucion();

        for (int i = 1000; i <= 5000; i += 1000) {

            Lectura.generarDataSet(i, PracticaMenu.peorcaso);

            ArrayList<Punto> p = Lectura.leerFichero("DataSet" + i + ".tsp");

            t1 = System.nanoTime();
            sol = Algoritmos.exhaustivoRecursivo((ArrayList<Punto>) p.clone());
            t2 = System.nanoTime();
            aux = (double) (t2 - t1) / 1000000;
            cadena = cadena + "\n" + i + "\t" + aux;

            t1 = System.nanoTime();
            sol = Algoritmos.exhaustivoPodaRecursivo((ArrayList<Punto>) p.clone());
            t2 = System.nanoTime();
            aux = (double) (t2 - t1) / 1000000;
            cadena = cadena + "\t" + aux;

            t1 = System.nanoTime();
            sol = Algoritmos.DyVRecursivo((ArrayList<Punto>) p.clone());
            t2 = System.nanoTime();
            aux = (double) (t2 - t1) / 1000000;
            cadena = cadena + "\t" + aux;

            t1 = System.nanoTime();
            sol = Algoritmos.DyVconPodaRecursivo((ArrayList<Punto>) p.clone());
            t2 = System.nanoTime();
            aux = (double) (t2 - t1) / 1000000;
            cadena = cadena + "\t" + aux;

            txtpane.setText(cadena);

        }

    }//GEN-LAST:event_btEjecutar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btejecutar;
    private javax.swing.JButton btvolvermenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JTextArea txtpane;
    // End of variables declaration//GEN-END:variables
}
