/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class MainVisual extends javax.swing.JFrame {

    private PracticaAMenu pA;
    private PracticaBMenu pB;
    
    /**
     * Creates new form MainVisual
     */
    public MainVisual() {
        initComponents();
        this.setLocation(300, 100);
        this.setTitle("\t\t\tPRACTICA 1 - AMC");
        
        pA = new PracticaAMenu(this);
        pB = new PracticaBMenu(this);
        
        cambiarPanel(pA);
    }
    
    public void cambiarPanel(JPanel p){
        p.setSize(786, 451 );
        p.setLocation(0, 0);
        
        panelCambio.removeAll();
        panelCambio.add(p, BorderLayout.CENTER);
        panelCambio.validate();
        panelCambio.repaint();
    }
    
    public void btCambiarPracticaToF(Boolean b){
        btcambiarpanel.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        lbtitulo = new javax.swing.JLabel();
        panelCambio = new javax.swing.JPanel();
        lbnombreprac = new javax.swing.JLabel();
        btcambiarpanel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelBase.setBackground(new java.awt.Color(204, 204, 204));

        lbtitulo.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        lbtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbtitulo.setText("PRACTICA 1");

        panelCambio.setPreferredSize(new java.awt.Dimension(786, 451));

        javax.swing.GroupLayout panelCambioLayout = new javax.swing.GroupLayout(panelCambio);
        panelCambio.setLayout(panelCambioLayout);
        panelCambioLayout.setHorizontalGroup(
            panelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCambioLayout.setVerticalGroup(
            panelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        lbnombreprac.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbnombreprac.setForeground(new java.awt.Color(0, 0, 0));
        lbnombreprac.setText("Practica A");

        btcambiarpanel.setBackground(new java.awt.Color(0, 0, 0));
        btcambiarpanel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btcambiarpanel.setForeground(new java.awt.Color(255, 255, 255));
        btcambiarpanel.setText("Cambiar entre Practica A y B");
        btcambiarpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambiarPanel(evt);
            }
        });

        javax.swing.GroupLayout PanelBaseLayout = new javax.swing.GroupLayout(PanelBase);
        PanelBase.setLayout(PanelBaseLayout);
        PanelBaseLayout.setHorizontalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(btcambiarpanel)
                .addGap(18, 18, 18)
                .addComponent(lbnombreprac, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        PanelBaseLayout.setVerticalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbnombreprac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btcambiarpanel)
                        .addComponent(lbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCambiarPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambiarPanel
        if(lbnombreprac.getText().equals("Practica B")){
            lbnombreprac.setText("Practica A");
            cambiarPanel(pA);
        }
        else{
            lbnombreprac.setText("Practica B");
            cambiarPanel(pB);
        }
    }//GEN-LAST:event_btCambiarPanel

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBase;
    private javax.swing.JButton btcambiarpanel;
    private javax.swing.JLabel lbnombreprac;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JPanel panelCambio;
    // End of variables declaration//GEN-END:variables
}
