/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Comun.Punto;

/**
 *
 * @author USER
 */
public class MostrarDataSetTabla extends javax.swing.JFrame {

    private DefaultTableModel dtm = new DefaultTableModel();
            
    /**
     * Creates new form MostrarDataSetTablaForm
     */
    public MostrarDataSetTabla() {
        initComponents();
        
        this.setTitle("TABLA DE PUNTOS");
        
        String s[] = {"ID","X","Y"};
        dtm.setColumnIdentifiers(s);
        
        ArrayList<Punto> puntos = PracticaMenu.dataSetA;
        
        for(int i=0; i < puntos.size(); i++){
            dtm.addRow(new Object[]{puntos.get(i).getIndice(), puntos.get(i).getX(), puntos.get(i).getY()});
        }
        
        tabtabla.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabtabla = new javax.swing.JTable();
        btvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "X", "Y"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabtabla.setRowHeight(25);
        jScrollPane1.setViewportView(tabtabla);

        btvolver.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btvolver.setText("Volver al Menu");
        btvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverMenu(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btvolver)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVolverMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverMenu
        this.setVisible(false);
    }//GEN-LAST:event_btVolverMenu

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btvolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabtabla;
    // End of variables declaration//GEN-END:variables
}
