/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import Comun.Punto;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.math.plot.Plot2DPanel;

/**
 *
 * @author USER
 */
public class PracticaAMenu extends javax.swing.JPanel {

    public static boolean peorcaso = false;
    public static ArrayList<Punto> dataSetA = null;

    private MainVisual mainV;

    /**
     * Creates new form PracticaAMain
     */
    public PracticaAMenu(MainVisual m) {
        initComponents();

        mainV = m;
    }

    public void setLbDataSet(String s) {
        lbdsmemoria.setText(s);
    }

    public String getLbDataSet() {
        return lbdsmemoria.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtitulo = new javax.swing.JLabel();
        btcompallestra = new javax.swing.JButton();
        btcargardataset = new javax.swing.JButton();
        btcompestra = new javax.swing.JButton();
        btcomp2estra = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        ckpeorcaso = new javax.swing.JCheckBox();
        lbtx1 = new javax.swing.JLabel();
        lbdsmemoria = new javax.swing.JLabel();
        btmostrardstabla = new javax.swing.JButton();
        btmostrardsgrafico = new javax.swing.JButton();
        btgraficascoste = new javax.swing.JButton();

        lbtitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbtitulo.setText("ALGORTIMOS DE BUSQUEDA Y ORDENACION");

        btcompallestra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btcompallestra.setText("Comparar todas las Estrategias");
        btcompallestra.setPreferredSize(new java.awt.Dimension(175, 30));
        btcompallestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprobarTodasEstrategias(evt);
            }
        });

        btcargardataset.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btcargardataset.setText("Cargar DataSet en Memoria");
        btcargardataset.setPreferredSize(new java.awt.Dimension(175, 30));
        btcargardataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarDataSet(evt);
            }
        });

        btcompestra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btcompestra.setText("Comprobar Estrategia");
        btcompestra.setPreferredSize(new java.awt.Dimension(175, 30));
        btcompestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprobarEstrategia(evt);
            }
        });

        btcomp2estra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btcomp2estra.setText("Comparar 2 Estrategias");
        btcomp2estra.setPreferredSize(new java.awt.Dimension(175, 30));
        btcomp2estra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprobarDosEstrategias(evt);
            }
        });

        btsalir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir(evt);
            }
        });

        ckpeorcaso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ckpeorcaso.setText("PEOR CASO");
        ckpeorcaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckpeorcasoActionPerformed(evt);
            }
        });

        lbtx1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbtx1.setForeground(new java.awt.Color(0, 0, 0));
        lbtx1.setText("DataSet cargado en memoria:");

        lbdsmemoria.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbdsmemoria.setForeground(new java.awt.Color(0, 0, 0));
        lbdsmemoria.setText("null");

        btmostrardstabla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btmostrardstabla.setText("Mostrar DataSet (Tabla)");
        btmostrardstabla.setPreferredSize(new java.awt.Dimension(175, 30));
        btmostrardstabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarDatasetTabla(evt);
            }
        });

        btmostrardsgrafico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btmostrardsgrafico.setText("Mostrar DataSet (Gráfico)");
        btmostrardsgrafico.setPreferredSize(new java.awt.Dimension(175, 30));
        btmostrardsgrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarDSGrafico(evt);
            }
        });

        btgraficascoste.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btgraficascoste.setText("Mostrar Gráficas de Coste");
        btgraficascoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGraficasCoste(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btgraficascoste)
                .addGap(145, 145, 145)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btcomp2estra, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btcompestra, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btcargardataset, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btcompallestra, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbtx1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbdsmemoria)
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btmostrardstabla, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckpeorcaso)
                                    .addComponent(btmostrardsgrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lbtitulo)
                                .addGap(61, 61, 61)
                                .addComponent(btcargardataset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbtx1)
                                    .addComponent(lbdsmemoria))
                                .addGap(32, 32, 32)
                                .addComponent(ckpeorcaso)))
                        .addGap(16, 16, 16)
                        .addComponent(btcompestra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btmostrardstabla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmostrardsgrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcompallestra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btcomp2estra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btgraficascoste, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    //
    private void btComprobarTodasEstrategias(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprobarTodasEstrategias
        CompararTodasEstrategias ctap = new CompararTodasEstrategias(mainV, this);
        mainV.cambiarPanel(ctap);
    }//GEN-LAST:event_btComprobarTodasEstrategias

    private void btCargarDataSet(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarDataSet
        CargarDataSet cdf = new CargarDataSet(this);
        cdf.setVisible(true);
    }//GEN-LAST:event_btCargarDataSet

    private void btComprobarEstrategia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprobarEstrategia

        if (dataSetA != null) {
            ComprobarEstrategia cep = new ComprobarEstrategia(mainV, this);
            mainV.cambiarPanel(cep);
        } else {
            JOptionPane.showMessageDialog(this,
                    "El array cargado en memoria esta vacio, no se puede ejecutar",
                    "INFO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btComprobarEstrategia

    //
    private void btComprobarDosEstrategias(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprobarDosEstrategias
        CompararDosEstrategias cdep = new CompararDosEstrategias(mainV, this);
        mainV.cambiarPanel(cdep);
    }//GEN-LAST:event_btComprobarDosEstrategias

    private void btSalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir
        System.exit(0);
    }//GEN-LAST:event_btSalir

    private void ckpeorcasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckpeorcasoActionPerformed
        if (peorcaso == false) {
            peorcaso = true;
            System.out.println("Peorcaso: " + peorcaso);
        } else {
            peorcaso = false;
            System.out.println("Peorcaso: " + peorcaso);
        }
    }//GEN-LAST:event_ckpeorcasoActionPerformed

    private void btMostrarDatasetTabla(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarDatasetTabla
        if (dataSetA != null) {
            MostrarDataSetTabla mdtf = new MostrarDataSetTabla();

            mdtf.setLocation(300, 100);
            mdtf.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this,
                    "El array cargado en memoria esta vacio, no se puede mostrar",
                    "INFO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btMostrarDatasetTabla

    private void btMostrarDSGrafico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarDSGrafico
        if (dataSetA != null) {
            Graficar g = new Graficar(dataSetA, null);
        } else {
            JOptionPane.showMessageDialog(this,
                    "El array cargado en memoria esta vacio, no se puede mostrar",
                    "INFO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btMostrarDSGrafico

    private void btGraficasCoste(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGraficasCoste
        new MostrarGraficaCoste();
    }//GEN-LAST:event_btGraficasCoste


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcargardataset;
    private javax.swing.JButton btcomp2estra;
    private javax.swing.JButton btcompallestra;
    private javax.swing.JButton btcompestra;
    private javax.swing.JButton btgraficascoste;
    private javax.swing.JButton btmostrardsgrafico;
    private javax.swing.JButton btmostrardstabla;
    private javax.swing.JButton btsalir;
    private javax.swing.JCheckBox ckpeorcaso;
    private javax.swing.JLabel lbdsmemoria;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JLabel lbtx1;
    // End of variables declaration//GEN-END:variables
}
