/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import Comun.Punto;

/**
 *
 * @author USER
 */
public class PracticaBMenu extends javax.swing.JPanel {

    private MainVisual mainV;
    public static boolean peorcaso = false;
    public static ArrayList<Punto> dataSetB = null;

    /**
     * Creates new form PracticaAMain
     */
    public PracticaBMenu(MainVisual m) {
        initComponents();

        mainV = m;
    }

    public void setLbDataSet(String s) {
        lbdsmemoria.setText(s);
    }

    public String getLbDataSet() {
        return lbdsmemoria.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtitulo = new javax.swing.JLabel();
        btcargardataset = new javax.swing.JButton();
        lbtx1 = new javax.swing.JLabel();
        lbdsmemoria = new javax.swing.JLabel();
        btunidireccional = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        btbidireccional = new javax.swing.JButton();
        btcomparar = new javax.swing.JButton();

        lbtitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbtitulo.setText("ALGORTIMOS VORACES");

        btcargardataset.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btcargardataset.setText("Cargar DataSet en Memoria");
        btcargardataset.setPreferredSize(new java.awt.Dimension(175, 30));
        btcargardataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcargardatasetbtCargarDataSet(evt);
            }
        });

        lbtx1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbtx1.setForeground(new java.awt.Color(0, 0, 0));
        lbtx1.setText("DataSet cargado en memoria:");

        lbdsmemoria.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbdsmemoria.setForeground(new java.awt.Color(0, 0, 0));
        lbdsmemoria.setText("null");

        btunidireccional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btunidireccional.setText("UNIDIRECCIONAL");
        btunidireccional.setPreferredSize(new java.awt.Dimension(175, 30));
        btunidireccional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnidireccional(evt);
            }
        });

        btsalir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirbtSalir(evt);
            }
        });

        btbidireccional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btbidireccional.setText("BIDIRECCIONAL");
        btbidireccional.setPreferredSize(new java.awt.Dimension(175, 30));
        btbidireccional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBidireccional(evt);
            }
        });

        btcomparar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btcomparar.setText("Comparar Algoritmos por Talla");
        btcomparar.setPreferredSize(new java.awt.Dimension(175, 30));
        btcomparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComparar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btcargardataset, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(lbtx1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbdsmemoria)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lbtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btunidireccional, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btbidireccional, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(btcomparar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbtitulo)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbtx1)
                            .addComponent(lbdsmemoria)
                            .addComponent(btcargardataset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btunidireccional, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btbidireccional, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)))
                .addComponent(btcomparar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btcargardatasetbtCargarDataSet(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcargardatasetbtCargarDataSet
        CargarDataSet cdf = new CargarDataSet(this);
        cdf.setVisible(true);
    }//GEN-LAST:event_btcargardatasetbtCargarDataSet

    private void btUnidireccional(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnidireccional
        if (dataSetB != null) {
            mainV.btCambiarPracticaToF(false);
            AlgortimosDireccionales adp = new AlgortimosDireccionales(mainV, this);
            adp.setLabelTitulo("Unidireccional");
            mainV.cambiarPanel(adp);
        } else {
            JOptionPane.showMessageDialog(this,
                    "El array cargado en memoria esta vacio, no se puede ejecutar",
                    "INFO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btUnidireccional

    private void btsalirbtSalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirbtSalir
        System.exit(0);
    }//GEN-LAST:event_btsalirbtSalir

    private void btBidireccional(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBidireccional
        if (dataSetB != null) {
            mainV.btCambiarPracticaToF(false);
            AlgortimosDireccionales adp = new AlgortimosDireccionales(mainV, this);
            adp.setLabelTitulo("Bidireccional");
            mainV.cambiarPanel(adp);
        } else {
            JOptionPane.showMessageDialog(this,
                    "El array cargado en memoria esta vacio, no se puede ejecutar",
                    "INFO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btBidireccional

    private void btComparar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComparar
        CompararAlgoritmosVoraces cav = new CompararAlgoritmosVoraces();
        cav.setVisible(true);
    }//GEN-LAST:event_btComparar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbidireccional;
    private javax.swing.JButton btcargardataset;
    private javax.swing.JButton btcomparar;
    private javax.swing.JButton btsalir;
    private javax.swing.JButton btunidireccional;
    private javax.swing.JLabel lbdsmemoria;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JLabel lbtx1;
    // End of variables declaration//GEN-END:variables
}
